[package]
name = "enum_primitive_derive"
version = "0.1.0"
authors = ["Andrei V <andrei@ptaxa.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version="0.15", features=["extra-traits"]}
quote = "0.6"
proc-macro2 = "0.4"
