image: ubuntu:18.04

before_script:
  - apt-get update
  - apt-get install -y -qq curl build-essential
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env

run_tests_stable:
  script:
    - rustup component add rustfmt --toolchain stable
    - cargo +stable fmt -- --check
    - cargo +stable test

run_tests_nightly:
  allow_failure: true
  script:
    - rustup install nightly
    - rustup component add rustfmt --toolchain nightly
    - cargo +nightly fmt -- --check
    - cargo +nightly test --features repr128
