image: ubuntu:18.04

before_script:
  - apt-get update
  - apt-get install -y -qq curl build-essential
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
  - rustup install stable
  - rustup install nightly

stages:
  - build
  - test

build_stable:
  stage: build
  script: cargo +stable build

build_nightly:
  stage: build
  script: cargo +nightly build

run_tests_stable:
  stage: test
  script: cargo +stable test

run_tests_nightly:
  stage: test
  script: cargo +nightly test --features repr128
