[package]
name = "enum_bits"
version = "0.1.0"
authors = ["Andrei V <andrei@ptaxa.net>"]
edition = "2018"

[dependencies]
enum_bits_derive = {path="./enum_bits_derive"}
lazy_static = "1.2"

[features]
repr128 = []
